# As of 2.4, don't forget to append these lines to english.json!
# it doesn't matter at all for functioning BUT it would help out translators a lot :) -T

splashText = [
    "I love cartoons!",
    "Did you watch BombStory?",
    "From Poland with love",
    "YATATATATATATA, KABOOM, KABOOM!",
    "No more spamming!",
    "Watch out for the bears!",
    "Where's Pizza?",
    "Lays Cheese Cayenne",
    "Also called BombSquad Reimagined",
    "BOINK!",
    "Flabbergasting!",
    "Enough talk...",
    "You primitive buccaneer!",
    "Have a great day.. or night!",
    "Relaxing, isn't it?",
    "efro is da best",
    "Let'sa go!",
    "Sucuking since 2015",
    "A random curse spawn",
    "Punch stamina no more!",
    "Imma lay in a bed for a while",
    "Have you heard about my modpack?",
    "I'm backed!",
    "SPLAT!",
    "Delete MEE6",
    "Shoutout to TheMikirog",
    "A little different...",
    "Vanilla+!",
    "Too many streaming services...",
    "I'm a master procrastinator!",
    "Glowing colors are gross",
    "Modded servers suck",
    "Off to visit yo motha!",
    "c o o r v a",
    "What did you just say?",
    "I finally coded something!",
    "Let there be... something",
    "Your hands will burn, trust me",
    "To do, to do, to do to do to do...",
    "I'm tired, get to the point",
    "Sauce?",
    "a.k.a funi physics",
    "It'll take you to the other side!",
    "Suddenly you're free to fly",
    "mamma mia",
    "I'm ready as I'll ever be",
    "that's pretty sus",
    "EMERGENCY MEETING!",
    "laughing out loud",
    "invalid syntax my ass",
    "Guten Tag!",
    "Hello again!",
    "floating landmine",
    "Who are you, really?",
    "Hell's comin' with me!",
    "soczkowyblogobs.blogspot.com",
    "Everything runs in a loop",
    "No one's ever really gone",
    "Tonight we strike!",
    "Holy macaroni",
    "Say my name...",
    "Waltuh?",
    "It's all good, man!",
    "I eat spaghetti code for dinner",
    "I need a pizza!",
    "Better with gamepad!",
    "Depression session prevention",
    "Mel gets his groove back!",
    "It's pretty dank!",
    "bsInternal is a lie",
    "Pain is weakness leaving the body",
    "good now kil te predisent",
    "Don't die too fast please!",
    "Make yourself happy again!",
    "Be a baby one more time",
    "Blobfish for the win!",
    "Punch and grab spam for the... no.",
    "Do you concur?",
    "KABLOOYE!",
    "SHAZAM!",
    "You wouldn't get it..",
    "Yellow is the new gray.",
    "POOTIS!",
    "POOTIS POW, HAHA!",
    "HEAVY IS DEAD!",
    "It's over, Hector.",
    "Ronnie's New Groove!",
    "Splash a.k.a New Juice-Boy",
    "We miss you, Yourself.",
    "Cerdo Gordo means Fat Pig",
    "I'm Breaking Bad.",
    "Stay hydrated!",
    "Breakfast and Juice",
    "What rhymes with extraordinary?",
    "Ice(land)Breaker",
    "TheYoSookiMikibreaker",
    "The Last Bombbender",
    "NewSquad, get some rest.",
    "You got a friend in me",
    "We are fighting dreamers!",
    "GO!!!",
    "Yeah, that's nice..",
    "Bombs away!",
    "Party madness!",
    "Alexa, play can can.",
    "Mountain King's hall.",
    "Offenbach made some good sheit.",
    "Gravity... falls!",
    "Adventure Time!",
    "Omnomnomnom",
    "The last wish.",
    "Booyakasha!",
    "Skadoosh",
    "Dream your dream.",
    "Shoutout to Alberto!",
    "Clayp#c*lyp$e",
    "Don't be toxic!",
    "Flutter exercise!",
    "Better Call SoK!",
    "The Owl House",
    "In-Sanic",
    "H4ZE!",
    "5KYB0-X",
    "ghg",
    "ogo",
    "lmao, lol, rofl or lamo",
    "We don't need a monitor",
    "It's proprietary...",
    "Now on GitHub!",
    "Team-Up!",
    "God Rest Ye Merry Gentlemen!",
    "Temporary...",
    "Mind The Gap!",
    "Inflatable Dwarf",
    "Stretchies!",
    "Rubber Jumper!",
    "Inside The Map!",
    "Sky High",
    "Pick it up.",
    "Fat Pig!",
    "Bakin' bacon...",
    "Blunder is coming!",
    "Cinnamon Shops",
    "Critique of Creation",
    "More form, less content!",
    "Ancient Stones",
    "SLEEP DEPRIVED",
    "ft. Visual Studio Code",
    "ft. Paint.net",
    "ft. Notepad++",
    "ft. Gimp",
    "ft. Paint Tool Sai 2",
    ":cowboy:",
    "Now with extra flutters!",
    "without S-Shaped bombs!",
    "Then he said \"It's explodinaring time\"",
    "if losing: help_SoK('win')",
    ":melly_cube:",
    "Yippie!",
    "sample text",
    "_ba? Where's that?",
    "can't properly rotate nodes!",
    "Press START to play!",
    "Hold A and B to start",
    "BombSquad Deluxe!",
    "PANDEMONIUM!",
    "Coffee is brewin'...",
    "NATYCHMIAST!",
    "RIGHT AWAY!",
    "Need a dispenser here!",
    "Professor Worminkle",
    "WOAH!!",
    "Take that, Overseer!",
    "Amusing!",
    "I stand faster than you run!",
    "Stay chaotic!",
    "Bomb-Jumping? Why?!",
    "Brprrprrprr...",
    "R.I.P Claypocalypse",
    "I wanna bomb your butt off!",
    "Deploy a dispenser here!",
    "Let's get 'em!",
    "ogo = ghg",
    "SO MANY TEXTS ON MODDED SERVERS!",
    "Also try JRMP!",
    "Also try Minecraft",
    "Also try Worms!",
    "Also try Pizza Tower!",
    "Also try ADIOS Amigos!",
    "Also try Stick Fight!",
    "Also try Overcooked!",
    "Also try Gang Beasts!",
    "Also try SpiderHeck!",
    "Also try Lovers in a Dangerous Spacetime!",
    "Also try Move or Die!",
    "Also try Rounds!",
    "Also try Castle Crashers!",
    "Also try Boomerang Fu!",
    "Also try Human Fall Flat!",
    "Also try Peggle!",
    "Also try BombSquad!... wait-",
    "Y'all ready to get funky!?!",
    "snoboi",
    "ROADMAP!!!",
    "Five Nights at Mel's",
    "Ready faster!",
    "You picked the wrong house, fool!",
    "A true successor to JRMP\n                    ~ TheMikirog",
    "SF6's soundtrack goes hard",
    "qwertyuiop",
    "qwerty",
    "wasd",
    "ENTER: An explodinary update!",
    "How will we port this to 1.7.20...",
    "Now with extra chaos!",
]