# They go here instead of the json file because screw you :cowboy:
changelogs = {
    "2.0": (
        "# BOMBSQUAD: EXPLODINARY 2.0 - FURBISH AND MO' UPDATE\n"
        "\n"
        "\n"
        "## GENERAL:\n"
        '   - Launched a Discord server! Added a join button in "How to Play" section!\n'
        "   - Now preloading new bomb models and textures.\n"
        "     The game loads half a second longer now, but the gameplay should be smoother when\n"
        "     taking out bombs for the first time, especially on weaker devices.\n"
        "   - Quick-Game button! You can play a one game FFA session by\n"
        '     simply clicking the button in "Play" menu (Thanks Mrmaxmeier for\n'
        "     creating the mod, and byANG3L for updating it).\n"
        "   - English is now a default language to avoid errors with setting up a language\n"
        "   - Deleted the option to change the language. It was useless anyway.\n"
        "   - Explodinary version display in Main Menu\n"
        "   - Changed powerup model to a simple box\n"
        "   - Changed flag pole and flag stand models\n"
        "   - A little angelic choir plays when curse is healed\n"
        "   - Sticky Bomb model was edited a bit\n"
        "   - New music for Runaround\n"
        "   - Character picker now has 4 columns instead of 3\n"
        "   - New splash texts added to the roster\n"
        "   - Teams are now Purple and Yellow once again\n"
        "   - Minor changes to the UI\n"
        "   - Changed the music for Epic Mode\n"
        "   - Changed the music for King of The Hill\n"
        "   - Changed the music for Onslaught\n"
        "   - Gyroscope camera is now auto-disabled\n"
        "   - Changed Explodinary Infinite Onslaught description at the start of the level\n"
        "   - Minor text changes\n"
        "   - New background in the lobby\n"
        "   - Changed some dudes colors in Play menu\n"
        "   - Got rid of Tournaments in Coop window. I left info why aren't they there\n"
        "   - Renamed Explodinary Infinite Onslaught to BSE Infinite Onslaught\n"
        "   - Subtle jazz plays when you're defeated in BSE Infinite Onslaught\n"
        "   - Explodinary gamemodes now have different button colors in coop menu, which leads us to..."
        "\n"
        "\n"
        "## GAMEMODES:\n"
        "   - New coop gamemode: Explodinary Infinite Runaround\n"
        "   - New coop gamemode: Kablooya Onslaught\n"
        "   - New coop gamemode: Kablooya Runaround\n"
        "   - New teams gamemode: Soccer"
        "\n"
        "\n"
        "## GAMEPLAY:\n"
        "   - Updated quick-turn plugin\n"
        "   - Changed jump cooldown from 250 to 150\n"
        "   - Reduced shatter light time and radius\n"
        "   - New bot: SoldatBot\n"
        "   - New bot: NoirBot\n"
        "   - New bot: MellyBot\n"
        "   - New bot: ExplodeyBotNoTimeLimit\n"
        "   - ChargerBot now randomly chooses between it's variants\n"
        "   - ExplodeyBot now randomly chooses between it's variants\n"
        "   - WaiterBot now throws bombs properly\n"
        "   - TNT is now slippery like before the 1.7.18 port"
        "\n"
        "\n"
        "## POWERUPS:\n"
        "   - New powerup: Flutter Bombs\n"
        "   - New powerup: Steam Bombs\n"
        "\n"
        "   Tacky Bomb:\n"
        "    - Blast radius has been changed from 0.65 to 0.55\n"
        "    - Blast magnitude has been changed from 2.0 to 1.5\n"
        "    - Updated visuals\n"
        "\n"
        "   Unwanted Present\n"
        "    - Blast radius has been changed from 1.55 to 1.65\n"
        "    - Chance of appearing has been changed from 1.2 to 1.0\n"
        "    - More noticeable animation\n"
        "\n"
        "   Curse:\n"
        "    - Changed curse blast radius from 3.0 to 3.35"
        "\n"
        "\n"
        "## MAPS:\n"
        "   - Added vanilla variations of The Pad, Step Right Up and Roundabout.\n"
        "     This was done for seamless online play. Modified ones are still\n"
        "     default in Explodinary, because they're more fair to play.\n"
        "   - Added subtle raillings to Cardfoart, Sunrise, and The Winged Blocks\n"
        "   - New map: Chop-Chop!\n"
        "   - New map: Snowhold\n"
        "   - New map: Soccer Stadium\n"
        "\n"
        "   Walleyville:\n"
        "    - Complete remake of the model, textures,\n"
        "      railings and background (thanks Neo!)\n"
        "\n"
        "   Sculpey Forest:\n"
        "    - Made the map a bit bigger\n"
        "    - Got rid of TNT\n"
        "    - Fixed janky collisions\n"
        "\n"
        "   Cardfoart:\n"
        "    - Slightly changed the map model to make\n"
        "      jumping over the gaps easier\n"
        "\n"
        "   Sunrise:\n"
        "    - New background\n"
        "    - Fixed janky powerup spawns\n"
        "\n"
        "   Block Fortress\n"
        "    - Moved the flag a bit closer to the middle\n"
        "\n"
        "   Doom Shroom:\n"
        "    - Now has a greenish tint"
        "\n"
        "\n"
        "## CHARACTERS:\n"
        "   - New character: Jackie Panty\n"
        "   - New character: Kronk Noir\n"
        "   - New character: Melly\n"
        "   - New character: Sneaky Snake\n"
        "   - New character: Soldier Boy\n"
        "   - New character: Zoette\n"
    ),
    "2.1": (
        "# BOMBSQUAD: EXPLODINARY 2.1 - TOXIC EASTER UPDATE\n"
        "\n"
        "\n"
        "## GENERAL:\n"
        "    - New gamemodes and addons are no longer read as plugins (thanks Temp!)\n"
        "    - Explodinary Easter Logo in the main menu\n"
        "    - Changed Kablooya Runaround preview texture\n"
        "    - Fixed skybox in the main menu"
        "\n"
        "\n"
        "## GAMEPLAY:\n"
        "   - Fixed powerup distribution"
        "\n"
        "\n"
        "## GAMEMODES:\n"
        "   New level: Endless Kablooya Runaround\n"
        "    - Infinite variant of Kablooya Runaround with reskinned map and more lives.\n"
        "   New level: Endless Kablooya Onslaught\n"
        "    - Infinite variant of Kablooya Onslaught with a new, reskinned map!"
        "\n"
        "\n"
        "## MAPS:\n"
        "   Sculpey Forest:\n"
        "    - Fixed some janky collisions... again.\n"
        "   Explodinary Infinite Runaround:\n"
        "    - Fixed some janky collisions\n"
        "   Galaxia Ultima:\n"
        "    - Added visible border\n"
        "    - Changed level definitions"
        "\n"
        "\n"
        "## POWERUPS:\n"
        " New powerup - Flutter Mines\n"
        "    - New variant of the land-mine, that does pitiful damage\n"
        " New powerup - Toxic Bombs\n"
        "    - Poison your opponents with this brand new bomb to make them lose\n"
        "      health over-time and make them more vulnerable to damage!"
        "\n"
        " Flutter Bombs:\n"
        "    - Now obliterates shields            \n"
        "    - Changed blast radius from 0.88 to 1\n"
        "    - Now they don't destroy powerups    \n"
        "    - Changed damage from 0 to 1"
        "\n"
        "\n"
        "## CHARACTERS:\n"
        "    - New character: H4ZE\n"
        "    - Zoette's icon is now higher quality"
    ),
    "2.2": (
        "# BOMBSQUAD: EXPLODINARY 2.2 - BALANCE BONANZA UPDATE\n"
        "\n"
        "\n"
        "## GENERAL:\n"
        "   - Updated to 1.7.19, woohoo! (Thanks Temp!)\n"
        "   - New BSE Coop Menu with all new levels! You can access it through Play section\n"
        "   - New BSE Settings Menu! You can access it through settings (Thanks Temp!)\n"
        "   - New Splash Texts\n"
        "   - Splash Text now changes every time you enter the main menu\n"
        "   - New text in Help menu\n"
        "   - New cursor design\n"
        "   - New music for Race\n"
        "   - New music for BSE Infinite Onslaught\n"
        "   - New music plays after defeat on Endless Kablooya levels\n"
        "\n"
        "\n"
        "## GAMEPLAY:\n"
        "   - Fixed the bug where flags in CTF reset themselves when the resetting player died\n"
        "     (thanks Temp!)\n"
        "   - Quick-Turn is now a lot more subtle to be more of a helping tool instead of the one\n"
        "     used primarily in attack\n"
        "   - TNT now respawns after exactly 20 seconds\n"
        "   - New bot: ToxicBot\n"
        "\n"
        "\n"
        "## New TNT Variants:\n"
        "   - Ice Box, which freezes and/or shatters enemies for 6 seconds\n"
        "   - Toxic Crate, which poisons people and deals massive damage\n"
        "     TNTs spawn in a certain order - Classic > Ice > Toxic\n"
        "     Memorize it to gain advantage!\n"
        "\n"
        "\n"
        "## POWERUPS:\n"
        "   - Unwanted Present\n"
        "       \" Let's be fair - this powerup sucked. You couldn't throw it anywhere,\n"
        "         it was annoying in coop and easily exploitable. I completely reworked it\n"
        '         so you can now throw it... and more. Check down below! "\n'
        "\n"
        "       - Changed density from 3.5 to 0.6, so it's now throwable\n"
        "       - Changed blast radius from 1.65 to 1.80\n"
        "       - Now gets dense when on the ground\n"
        "       - Now can't be picked up\n"
        "       - Now can't get blown up by other bombs\n"
        "       - Now fuse time activates when thrown\n"
        "       - Confetti sound effect when thrown\n"
        "       - Updated visuals\n"
        "       - Bigger scorch after explosion\n"
        "\n"
        "   - Lite Mines\n"
        '       " Lite Mines had their good moments, but were mainly useless and just a\n'
        "         downgrade to Land Mines, despite higher package.\n"
        '         Now they also counter shields and have fixed damage! "\n'
        "\n"
        "       - Now deals exactly 400 damage, so it's more consistent\n"
        "       - Now they stun people!\n"
        "       - Changed blast magnitude from 1.5 to 0.5.\n"
        "\n"
        "   - Flutter Mines\n"
        '       " Their problem was similar to the one that Lite Mines had...\n'
        "         downgrade from Land Mines. Sooo.. they counter\n"
        '         shields and are way more comfortable and useful! "\n'
        "\n"
        "       - Changed density from 1.25 to 1\n"
        "       - Now obliterate shields\n"
        "       - Now pack of 3, stackable to 6\n"
        "       - Now doesn't fling flags (Thanks Temp!)\n"
        "       - New magnitude mechanics (Thanks Temp!)\n"
        "       - Now fling powerups (Thanks Temp!)\n"
        "\n"
        "   - Toxic Bombs\n"
        '       "To be honest, I thought Toxic Bombs were alright,\n'
        "        but looking back at it - they deserved a little buff\n"
        '        and more synergy mechanics."\n'
        "\n"
        "       - Changed blast radius from 1.1 to 1.15, so it's closer to Ice Bomb in terms of feel\n"
        "       - Now players poisoned and cursed at the same time give poison to others with their blast.\n"
        "\n"
        "   - Flutter Bombs\n"
        "       - Now deal 25 damage on hit\n"
        "       - Now fling powerups (Thanks Temp!)\n"
        "       - New magnitude mechanics (Thanks Temp!)\n"
        "       - Now doesn't fling flags (Thanks Temp!)\n"
        "\n"
        "\n"
        "## GAMEMODES:\n"
        "   - New Coop gamemode: Pathway Pandemonium\n"
        "       Survive as long as you can in this new, endless Runaround level,\n"
        "       where difficulty relies on how many days you lasted. Day cycle included!\n"
        "       Daily reminder!\n"
        "\n"
        "\n"
        "## MAPS:\n"
        "   - New map: Baboon Face\n"
        "   - New map: Sour Flower\n"
        "\n"
        "   * BSE Infinite Runaround:\n"
        "       - Now powerups spawn higher to avoid collision glitches\n"
        "       - Fixed some collisions\n"
        "       - TNT spawns in a different place\n"
        "       - The exit is a bit further away\n"
        "\n"
        "\n"
        "## CHARACTERS:\n"
        "   - New Spaz variant - Spazzy Toxicant\n"
    ),
    "2.3": (
        "# BOMBSQUAD: EXPLODINARY 2.3 - CHAOTIPALOOZA UPDATE\n"
        "\n"
        "\n"
        "## GENERAL:\n"
        "   - New addition: CHAOS MODE!"
        "\n"
        "     Unleash some wacky, chaotic events upon your game!\n"
        "     Every few seconds some weird stuff happens randomly. Prepare for the unpreparable!\n"
        "     You can turn Chaos Mode on and off in the BSE Settings (off by default)."
        "\n"
        "\n"
        "   - Brought back old BombSquad game announcer!\n"
        "     You can turn him on and off in the BSE Settings (off by default)."
        "\n"
        "\n"
        "## POWERUPS:\n"
        "   - New powerup: Vital Bomb!\n"
        '       " Make yourself and your bombs stronger with a bomb made of herbs and flowers!\n'
        "         Overheal your allies and turn powerups to precious vitamins!\n"
        '         This bomb makes you punch faster and more immune to damage! "\n'
        "\n"
        "## GAMEMODES:\n"
        "   Pathway Pandemonium\n"
        "       - Now up to 5 players can play this gamemode!"
        "\n"
        "\n"
        "## MAPS:\n"
        "   - New map: Fuse Cruise"
    ),
    "2.4": (
        "# BOMBSQUAD: EXPLODINARY 2.4 - THE ADVENTURE UPDATE\n"
        "\n"
        "\n"
        "## GENERAL:\n"
        "     EXPLODINARY CAMPAIGN!"
        "\n"
        "     \"Mysterious Overseer manifested in BombLand, and started corrupting it's residents.\n"
        "      Fate of the world lies in your hands. Go on a journey through the entire BombLand,\n"
        "      defeat Overseer's army, take him down, free the world, and become a hero!\"\n"
        "\n"
        "     BSE Campaign can be accessed through BSE Coop menu\n"
        "     When you beat the campaign, you can expect some nice trophies. Have fun!"
        "\n"
        "\n"
        "     New map-gimmick: Jump-Pad!\n"
        "      Propel yourself upwards to gain advantage over your enemy, or to\n"
        "      traverse the map faster! Time your jump right to get launched even more!"
        "\n"
        "\n"
        "     New map-gimmick: Slingshot!\n"
        "      When you touch it, you get launched forward with incredible force.\n"
        "      Funny physics and funny moments generator!!"
        "\n"
        "\n"
        "     New mode: Hub!\n"
        "      Chill with your friends on a nice island; play basketball,\n"
        "      train your skills, goof around or just sit, talk and relax.\n"
        "      12 players max! You can access Hub via Play menu."
        "\n"
        "\n"
        "     Big Chat tweaks!\n"
        "      - When sending a message, it appears above your character.\n"
        "        Your character also waves it's arms and makes a sound :)\n"
        "        Capitalize your text to make your character scream!\n"
        "      - New commands:\n"
        "       *explode*\n"
        "       *disappear*\n"
        "       *faint*\n"
        "       *die*\n"
        "      - Party Window is now smaller so you see the screen more clearly\n"
        "      - New Party icon - a speech bubble"
        "\n"
        "\n"
        "     Chaos Rework!\n"
        "      - Chaos was remade from the ground up, bringing in a lot of changes and\n"
        "        optimization to the experience! but not only that...\n"
        "      - You're now able to make your own Chaos Events! Check your mods folder for a new\n"
        '        "Chaos" subdirectory and explore the provided scripts to learn how to make yours!\n'
        "      - Errors that may occur with events no longer halt the entire mode,\n"
        "        instead, some errors are printed to the console and thats it!\n"
        "      - You can now choose between all these new settings as well:\n"
        "        * Announce event: Yes / No\n"
        "        * Timer position: TopLeft / TopMiddle / TopRight /\n"
        "                          BottomLeft / BottomMiddle / BottomRight\n"
        "        * Event List position: Left / Right\n"
        "      - Some events have been changed and readjusted to improve gameplay. Check them out!\n"
        "      - Added new Sugarcube Hailstorm music variant for coop"
        "\n"
        "\n"
        "      Misc:\n"
        "      - Added new music\n"
        "      - Slight event renaming"
        "\n"
        "\n"
        "      Event changes:\n"
        "        Hello There!:\n"
        "          - Plays a nice, scary sound effect now"
        "\n"
        "\n"
        "     Main Menu tweaks!\n"
        "      - New Main Menu layout\n"
        "      - New Main Menu themes! They change music and appearance.\n"
        "        You can choose one in BSE Settings\n"
        "      - Main Menu now changes at night. It's based on your device's clock.\n"
        "        Night appearance of course affects all Main Menu themes"
        "\n"
        "\n"
        "     All languages can be loaded once again!\n"
        "      - We (hopefully) unhardcoded all strings so they can be translated\n"
        "        to different languages! Right now we've only made Polish and Spanish\n"
        "        translations as that's as far as our knowledge goes, so if you are\n"
        "        fluent in any other language and want to help us translate, let us know!\n"
        '      - All "unsupported" languages are shown red while choosing them in settings'
        "\n"
        "\n"
        "     - New, revamped BSE Coop Menu, which includes Explodinary Campaign now\n"
        "     - New, revamped Play Menu\n"
        "     - You can now disable More Particles in BSE Settings if your FPS are choppy\n"
        "     - New tips and trivia in BSE Coop menu\n"
        "     - New tips appearing in lobby\n"
        "     - New credits for Explodinary\n"
        "     - Added all previous changelogs to Changelog section :^)\n"
        "     - Changed Health powerup's icon to a green cross due to legal reasons\n"
        '     - Changed "Stayin Alive" achievement icon to a green cross as well\n'
        "     - Added a subtle info about modified map counterparts in map select window"
        "\n"
        "\n"
        "##GAMEPLAY:\n"
        "   - LOTS of new, satisfying sound effects. Go check them out!\n"
        "   - Character dependent sound effects on hit and impact\n"
        "   - Character dependent visuals on hit and impact\n"
        "   - Frozen and Cursed players freeze others with their blast\n"
        "   - BSE powerups and TNTs no longer spawn in Vanilla coop\n"
        "   - Kablooya modes have been optimized, removing some discrepancies, such as \n"
        "     Onslaught not playing defeat music, unlike it's infinite counterpart.\n"
        "   - Balanced some bot points multipliers"
        "\n"
        "\n"
        "##GAMEMODES:\n"
        "   New Coop gamemode: Timey Bombnuts\n"
        "       A new Infinite Onslaught variant. Get the best score before the time runs out!"
        "\n"
        "\n"
        "   New Coop gamemode: Route Roulette\n"
        "       A new Runaround variant with a dedicated map that includes Jump-Pads!\n"
        "       Score 2000 points to unlock a new character as a prize!"
        "\n"
        "\n"
        "   New FFA and Teams gamemode: Rocket Hell\n"
        "       Kill set number of enemies with Cloud Cuffs!"
        "\n"
        "\n"
        "   New FFA and Teams gamemode: Arms Race\n"
        "       Gamemode featured in Maxmeier's Mod Manager and JRMP makes a comeback!\n"
        "         Shoutout to Freakyyyy for 1.7 port"
        "\n"
        "\n"
        "   Race:\n"
        "    - Added new setting for Mine Variants spawning\n"
        "    - Added new setting for players to spawn with Dash-O-Matic equipped"
        "\n"
        "\n"
        "## POWERUPS:\n"
        "   NEW POWERUP - Cloud Cuffs!\n"
        "    Turns your punches into small rockets that you can shoot every second!\n"
        "    Great compromise between punches and bombs, and they're\n"
        "    good for turning on some sick chain reactions quickly!\n"
        "    Note: this powerup is disabled on Happy Thoughts and Galaxia Ultima"
        "\n"
        "\n"
        "   NEW POWERUP - Dash-O-Matic!\n"
        "    This powerup lets you dash forward a few times!\n"
        "    Useful for gaining speed for your punches and traversing the map faster!\n"
        "    Note: this powerup is disabled on Happy Thoughts, Galaxia Ultima and in Race gamemode."
        "\n"
        "\n"
        "   NEW POWERUP - Cluster Bombs!\n"
        "    New bomb that emits explosive clusters upon explosion!"
        "\n"
        "\n"
        "   NEW POWERUP - Glue Mine!\n"
        "    A new mine variant that makes a sticky glue puddle upon explosion!"
        "\n"
        "\n"
        "   Vital Bomb:\n"
        "     - Removed the perk of buffed durability\n"
        "     - Now a sound plays when the player is vitalized\n"
        "     - Now a sound plays when the player is unvitalized\n"
        "     - Now your punch cooldown is still lower when you equip gloves or cuffs\n"
        "     - Now gives one extra dash when Dash-O-Matic is already equipped\n"
        "     - Now buffs and nerfs bombs even more\n"
        "     - Buffed and nerfed bombs have more noticeable visuals now\n"
        "     - Buffed bombs explosions now look more powerful and noticeable\n"
        "     - Vitamin powerup has a new, yellow texture"
        "\n"
        "\n"
        "   Ice Bomb:\n"
        "     - Now freezes powerups and makes them slippery instead of destroying them"
        "\n"
        "\n"
        "   Lite Mines:\n"
        "     - Now makes powerups sparky instead of destroying them\n"
        "       Sparky powerups electrocute players for one second when picked up"
        "\n"
        "\n"
        "   Steam Bomb:\n"
        "     - New sound when close to explosion\n"
        "     - Changed blast power from 1.3 to 1.5"
        "\n"
        "\n"
        "   Toxic Bomb:\n"
        "     - Now people who die when poisoned turn green and emit slime chunks\n"
        "     - Removed the perk of faster punches for poisoned players\n"
        "     - Poisoned players emit green chunks when hit"
        "\n"
        "\n"
        "   Misc:\n"
        "   - New, custom particle system to make visuals more appealing\n"
        "   - Added Glue Mine to the Chaos Powerup Distribution\n"
        "   - Changed the description of Chaos Powerup Distribution\n"
        "   - Small tweak of Competitive Powerup Distribution description"
        "\n"
        "\n"
        "## TNT VARIANTS:\n"
        "   NEW TNT VARIANT - Glue Container!\n"
        "    This one spawns last. Shoots a bunch of glue upon explosion,\n"
        "    while also doing massive damage to your opponents!"
        "\n"
        "\n"
        "   Ice Box:\n"
        "    - Changed blast magnitude from 1 to 1.1"
        "\n"
        "\n"
        "   - You can now turn off TNT Variants in BSE Settings (FFA and Teams only)"
        "\n"
        "\n"
        "## CHARACTERS:\n"
        "     - New, secret character unlockable by completing the BSE Campaign"
        "\n"
        "\n"
        "     - New, secret character unlockable by scoring 2000 points in Route Roulette"
        "\n"
        "\n"
        "     - New characters: Helpy and Spencer\n"
        "        Both are obtainable in store."
        "\n"
        "\n"
        "     - New Bones variant: Bosbone\n"
        "        Note: Bones must be bought to access this variant"
        "\n"
        "\n"
        "     - New character: Crispin\n"
        "        A tribute to PotatoVFX. We'll miss you, buddy."
        "\n"
        "\n"
        "    - Dominic:\n"
        "      - Complete redesign\n"
        "      - New icon"
        "\n"
        "\n"
        "     - New icons for:\n"
        "        o Kronk Noir\n"
        "        o Master Serpent\n"
        "        o Melly\n"
        "        o Melvin\n"
        "        o Mictlan\n"
        "        o Spazzy Toxicant\n"
        "        o Z03 3000"
        "\n"
        "\n"
        "## MAPS:\n"
        "    NEW MAP - Sunset\n"
        "     Includes Jump-Pads!"
        "\n"
        "\n"
        "    NEW MAP - Clay-ish Donut\n"
        "     A new map for Race and FFA!"
        "\n"
        "\n"
        "    *Sunrise:\n"
        "     - Added Jump-Pads\n"
        "     - Tweaked level definitions"
        "\n"
        "\n"
        "    *Cardfoart:\n"
        "     - Added Jump-Pads"
        "\n"
        "\n"
        "    *The Pad:\n"
        "     - Added Jump-Pads"
        "\n"
        "\n"
        "    *Soccer Stadium:\n"
        "     - Added Slingshots"
        "\n"
        "\n"
        "    *Chop-Chop!:\n"
        "     - Tweaked level definitions"
        "\n"
        "\n"
        "    *Where Eagles Dare:\n"
        "     - Tweaked the camera a bit"
        "\n"
        "\n"
        "   *Kablooya Onslaught and Endless Kablooya Onslaught:\n"
        "    - Map definition tweaks to make bots less suicidal"
        "\n"
        "\n"
        "   *Fuse Cruise:\n"
        "    - Added dedicated music\n"
        "    - Added visuals and sound effect when falling into the water\n"
        "    - Added sea ambience\n"
        "    - Fixed janky flag spawn"
        "\n"
        "\n"
        "   *Galaxia Ultima:\n"
        "    - Border now matches map edges perfectly"
        "\n"
        "\n"
        "   *Pathway Pandemonium:\n"
        "    - Enhanced map texture\n"
        "    - Fixed a visual error"
        "\n"
        "\n"
        "   *Doom Shroom:\n"
        "    - Added a PVP variant with smooth collisions"
    ),
    "2.5": (
        "# BOMBSQUAD: EXPLODINARY 2.5 - THE DRIP AND STYLISH UPDATE [WIP]\n"
        "\n"
        "\n"
        "## GENERAL:\n"
        "    - Removed sex."
    ),
}
